site_name: Diamonds (Over 60s Erging Group) Members Guide
site_url: https://diamonds-erging.github.io/members-guide/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

nav:

  - Home: index.md

  - Membership:
    - Joining: membership/joining.md
    - Benefits: membership/benefits.md
    - Kit: membership/kit.md
  
  - Club Structure:
    - Admin Team: club/admin-team.md
    - Contacts: club/contacts.md
    - Facebook Group Rules: club/facebook-group-rules.md

  - Training:
    - Training Plans: training/plans.md
    - Technique: training/technique.md
    - Terminology: training/terminology.md
    - Rowing On Slides: training/slides.md
    - Sprinting: training/sprinting.md
    - Aerobic Development: training/aerobic-development.md
    - Pacing: training/pacing.md
    - Erg Maintenance: training/erg-maintenance.md
      
  - Competitions & Challenges:
    - Cross Team Challenge: challenges/ctc.md
    - Equalizer: challenges/equalizer.md
    - Decathlon: challenges/decathlon.md
    - CrossErg: challenges/crosserg.md
    - Resolution Row: challenges/resolution-row.md
    - Annual Meters: challenges/annual-meters.md
    - Concept2 Challenges: challenges/c2-challenges.md
